# decrypt_secrets.yml
#
- name: install git
  action: yum name=git state=latest

- name: install openssl
  action: yum name=openssl state=present

- name: install DVLA secrets
  git: repo={{ GIT_REMOTE_STRING }} dest=/etc/DVLA/secrets version=HEAD

- name: create conf directory for vehicles-secrets
  file: path=/opt/vehicles-online/conf state=directory

- name: Decrypt vehiclesOnline.conf
  shell: /etc/DVLA/secrets/decrypt-file /etc/DVLA/secrets/ui/dev/vehiclesOnline.conf.enc /opt/vehicles-online/conf/vehiclesOnline.conf {{ GIT_SECRET_PASSPHRASE }}

