# install-microservice.yml
#
- name: install java-1.7.0-openjdk
  yum: name=java-1.7.0-openjdk

- name: install vehicles-online
  shell: cd /vagrant/target && rpm -Uhv *.rpm --force

- name: start vehicles-online
  service: name=vehicles-online state=running

- name: start monit
  service: name=monit state=restarted

