#!/bin/bash

set -o errexit

export JAVA_OPTS="-Dspecs2.color=false -Dsbt.log.format=true -Dsbt.log.noformat=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128 -XX:MaxPermSize=1024M $JAVA_OPTS"

sbt -Dsbt.log.noformat=true clean test gatling dist publish

rm -rf target/*.rpm
./rpm-build/jenkins_job_make_rpm
